### ISSUE TITLE
[FEAT] Card 컴포넌트, 스토리북

### ISSUE THREAD

**Issue by keemsebin** [dnd-side-project/dnd-11th-7-frontend#99]
## TODO

- Card 컴포넌트, 스토리북

**Comment by jhsung23** [comment]
혹사 이건 어떤 용도의 카드인가요? 저희 디자인에 카드 스러운게 많아서용

**Comment by keemsebin** [comment]
크게 봤을 때 3가지가 있을 것 같습니당
1. 모임의 정보를 나열하는 용도
<img width="253" alt="스크린샷 2024-08-20 오후 8 24 55" src="https://github.com/user-attachments/assets/69d90add-a47c-4d60-ab55-67a4a3812548">

2. 째깍 이모지 & 모임의 정보를 나열하는 용도

<img width="220" alt="스크린샷 2024-08-20 오후 8 25 06" src="https://github.com/user-attachments/assets/ff2e55e5-075f-40d8-863a-4674bb76b612">

3. 멤버들 나열할 때 사용하는 용도

<img width="549" alt="스크린샷 2024-08-20 오후 8 25 16" src="https://github.com/user-attachments/assets/58022050-cead-42cc-b0e6-fe117cca819a">

**Comment by keemsebin** [comment]
해당 컴포넌트는 따로 분리하는 게 좋을 것 같아서 포함시키지 않으려고 합니당

<img width="323" alt="스크린샷 2024-08-20 오후 8 29 21" src="https://github.com/user-attachments/assets/7fa940a9-d3dd-4324-a20e-e1c2eb7bd50e">

**Comment by jhsung23** [comment]
그럼 요 티켓에서 컴포넌트 3개 만든다고 알고 있으면 될까용??

**Comment by keemsebin** [comment]
현재 크게 차이점이 요 두가지라서 Card 컴포넌트 내에서 Props에 따라 다르게 하려고 했어욥!!
1. 째깍 아이콘 유무
2. border, backgroud-color

**Comment by keemsebin** [comment]
계속 생각하다 보니 Card, MemberCard 로 나누면 좋을 것 같다는 생각도 들어요! 분리하는게 확실히 더 좋을 거 같은데 어떠신가용??
1. 째각 아이콘 유무에 따른 Card 컴포넌트 
<img width="100" alt="스크린샷 2024-08-20 오후 8 25 06" src="https://github.com/user-attachments/assets/9741b674-837a-4772-8213-9bb807cf56de">
<img width="100" alt="스크린샷 2024-08-20 오후 8 24 55" src="https://github.com/user-attachments/assets/d94d539a-00e3-4512-9082-d116ceaa1073">

2. MemberCard Component 
<img width="300" alt="스크린샷 2024-08-20 오후 8 25 16" src="https://github.com/user-attachments/assets/b85422d1-36de-40f6-ba31-b2d57b0c4fd3">

**Comment by jhsung23** [comment]
넵넵

Card라는 커먼한 이름 아래 도메인 로직(아직은 UI 작업 뿐이지만)이 들어가는 듯하여 feature 컴포넌트로 보고 분리해도 좋을 것 같습니다~
